variables:
  DOCKER_BUILDKIT: 1
  APP_NAME: "p2c-fe"
  PORT: "3001"
  NETWORK: "p2c-net"
  ENV_FILE: ${env}
  DEVELOP_BRANCH: develop

workflow:
  rules:
    - if: "$CI_MERGE_REQUEST_IID"
    - if: "$CI_COMMIT_BRANCH == $DEVELOP_BRANCH"

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - cp ${ENV_FILE} .env
    - docker --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker stop $APP_NAME || true
    - docker rm $APP_NAME || true
    - docker pull $CI_REGISTRY_IMAGE
    - docker container run -d  --network $NETWORK --name $APP_NAME -p $PORT:80 $CI_REGISTRY_IMAGE
    - docker logout
  tags:
    - shell
  only:
    - develop
