name: deploy

on:
  push:
    branches: [ develop ]
    
jobs:
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Setup code
        uses: actions/checkout@v4
        
      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.0.0'
      
      - name: Run test
        run: |
          npm install
          echo "TEST SUCCESSFULLy"
        
  build-dev:
    needs: test-dev
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build..."
        
  deploy-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy..."
