name: deploy

on:
  push:
    branches: [ develop ]
    
jobs:
  test-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup code
        uses: actions/checkout@v4
        
      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.0.0'
      
      - name: Run test
        run: |
          npm install
        
  build-dev:
    # needs: test-dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup code
        uses: actions/checkout@v4
        
      - name: Build and push docker image to ghcr
        uses: elgohr/Publish-Docker-Github-Action@v4
        with: 
          name: ${{ github.repository }}/p2c-github
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: dev
          dockerfile: Dockerfile
           
        
  deploy-dev:
    needs: build-dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Deploy
        run: echo "Deploy..."
