name: build

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with: 
          node-version: "18.13.0"
      - name: Install npm
        run: |
          npm install
        env:
          CI: true
      - name: Publish to GITHUB packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: lengocson131002/path-to-career
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
