name: build

on:
  pull_request:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with: 
          node-version: "18.13.0"
      - name: Caching npm packages
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm
        run: |
          npm install
        env:
          CI: true
      - name: Publish to GITHUB packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: lengocson131002/path-to-career/p2c
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if : github.ref == 'refs/heads/master'
    steps:
      - name: Deploy package to VPS Server
        uses: appleboy/ssh-action@v1.0.0
        env:
          CONTAINER_NAME: p2c-github
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN, CONTAINER_NAME
          script: |
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker pull docker.pkg.github.com/lengocson131002/path-to-career/p2c
            docker run -d --name $CONTAINER_NAME --restart unless-stopped -p 3002:80 docker.pkg.github.com/lengocson131002/path-to-career/p2c
