name: build

on:
  push:
    branches: [ develop, staging, master]
      
jobs:
  build-dev:
    environment:
      name: develop
      url: https://p2c.site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        run: echo ${{ env.ENVIRONMENT }}
        
        with: 
          node-version: "18.13.0"
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Caching npm packages
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm
        run: |
          npm install
        env:
          CI: true
      - name: Publish to GITHUB packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
  deploy-dev:
    needs: build-dev
    environment:
      name: develop
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy package to VPS Server
        uses: appleboy/ssh-action@v1.0.0
        env:
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE:  ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN, CONTAINER_NAME
          script: |
            docker login ${{ env.IMAGE_REGISTRY}} -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker pull $IMAGE
            docker run -d --name $CONTAINER_NAME --restart unless-stopped -p 3002:80 $IMAGE
